### ISSUE TITLE
Automatically install target if specified when using `--version-range`

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#107]
If the `--target` flag is used when using `--version-range`, it makes sense to automatically install the target. This is a no-op if it is already installed, so the additional cost is near zero.

I think this is a reasonable addition given that `--version-range` is intended to be used in CI, and `cargo-hack` already knows what versions are being used. Without this feature, the logic for what versions need the target installed would need to be duplicated.

This would, of course, fail if the target doesn't exist in a given release. That error would presumably be passed on the same way others are.

**Comment by taiki-e** [comment]
This seems reasonable to me!

**Comment by taiki-e** [comment]
Published 0.5.2 that fixes this issue.
