### ISSUE TITLE
Option to run `cargo clean` between different compiler versions

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#119]
When running a full CI check, I'm running out of space on disk (with GitHub Actions). Given that a single compiler version only consists of 384 checks (not even full compilations), this shouldn't be an issue, but I'm checking on all releases since MSRV, which in my case is six full runs (2304 total checks).

If there were an option to run `cargo clean` between different compiler versions, that would be awesome. It could compliment `--clean-per-run`, which already exists. Perhaps `--clean-per-version`?

(yes, I know I could split the CI into multiple jobs. I likely will if you don't like this idea)

**Comment by taiki-e** [comment]
Added in 0.5.5 (#120).

**Comment by jhpratt** [comment]
Thanks as always!
