### ISSUE TITLE
Deduplicate diagnostics

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#130]
Similar to rust-lang/cargo#9675. I think this is possible by doing something like

- Use `--message-format=json` on all commands
- Store the diagnostic in a set
- Emit the diagnostic if and only if the diagnostic was not previously in the set

This is a ten-second thought, so I've probably missed something. I also don't know how easy it is to emit a diagnostic once you're using `--message-format=json`, which I imagine is the caveat here.

**Comment by taiki-e** [comment]
I would prefer not to do this for the following reasons:

- While cargo deduplicates warnings under the same build conditions, in cargo-hack, the implementation needs to deduplicate warnings under different build conditions (feature flags, rustc versions, etc.). If the build conditions are different, even if the warnings look the same, the necessary fixes may be completely different.
- In cargo-hack, the implementation also needs to clarify which warnings duplicate which build's warnings.
- The amount of builds processed by cargo-hack can be huge. Especially for large projects where warnings are not denied by CI, memory consumption may become a problem if all diagnostics are saved.

Anyway, thanks for the suggestion.
