### ISSUE TITLE
express mutually exclusive features

### ISSUE THREAD

**Issue by robjtede** [taiki-e/cargo-hack#132]
I don't really understand what `--group-features` is doing just from the readme or help output so it's possible I'm using it wrong and that this is possible already.

I want to provide an optional TLS backend `openssl` or `rustls` but they emit conflicting code so using `--feature-powerset` is not working out yet.

TIA

**Comment by taiki-e** [comment]
I don't think there is currently a way to do this with a single command. (`--group-features` treats the specified features as if it were a single feature.)

If you are okay with splitting it into multiple commands, I think you can express this by combining `--skip`(`--exclude-features`) and `--features`.

```sh
# All combinations that contain openssl and do not contain rustls.
cargo hack build --feature-powerset --features openssl --skip rustls
# All combinations that contain rustls and do not openssl.
cargo hack build --feature-powerset --features rustls --skip openssl
# All combinations that do not contain both openssl and rustls.
cargo hack build --feature-powerset --skip openssl,rustls
```

**Comment by taiki-e** [comment]
https://github.com/taiki-e/cargo-hack/issues/132#issuecomment-947800980

>> If it is not possible, consider adding a compile error to detect this scenario.

Btw, #115 is a feature request to check that a proper compilation error occurs in such cases.
