### ISSUE TITLE
Warning about non-existing feature `''` if `--skip ''` is specified

### ISSUE THREAD

**Issue by Nemo157** [taiki-e/cargo-hack#163]
I'm setting up some reusable workflows for my projects and as part of that need to pass in a parameterized `--skip` flag. Previously on 0.3.9 having this empty for projects that don't need to skip any features worked without any warnings, now on `0.5.17` this outputs a warning:

```
> cargo hack check --feature-powerset --skip ''
warning: specified feature `` not found in package `self-test`
info: running `cargo check --no-default-features` on self-test (1/1)
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

It would be nice if an empty string was considered the same as not passing the flag.

**Comment by taiki-e** [comment]
Fixed in 0.5.18 (#164). Thanks for the report!
