### ISSUE TITLE
`rust-version.workspace` does not work

### ISSUE THREAD

**Issue by vilgotf** [taiki-e/cargo-hack#165]
The new Cargo 1.64 `<key>.workspace` syntax does not work with cargo-hack (errors with the message below)
```
failed to parse `rust-version` field from manifest
```

**Comment by taiki-e** [comment]
Thanks for the report. Workspace Inheritance (https://github.com/rust-lang/cargo/pull/10859) is just become available today in stable version and is not yet supported in cargo-hack.
