### ISSUE TITLE
Support multi-target checks, builds, etc.

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#167]
With the release of Rust 1.64 today, cargo supports multi-target builds. [This is noted in the release notes](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds). It's a _super_ useful feature at first glance, and it would be great if `cargo hack` could pass this on to cargo proper.

**Comment by taiki-e** [comment]
Supported in 0.5.20 (#168).

**Comment by jhpratt** [comment]
Thank you for the implementation, and the speed of doing so! I just tried it out for the first time. Overall, it works exactly as I'd expect. One nit: the "(x/y)" counter does not take the target duplication into account on older compilers.

**Comment by taiki-e** [comment]
> One nit: the "(x/y)" counter does not take the target duplication into account on older compilers.

Good catch! Fixed in 0.5.21 (#169).
