### ISSUE TITLE
Allow outputting the commands that will be run without running them

### ISSUE THREAD

**Issue by leighmcculloch** [taiki-e/cargo-hack#172]
It would be really helpful to allow outputting the commands that will be run without running them.

That way the commands could be used to generate a dynamic matrix for GitHub Actions, and the feature runs could be split over multiple instances.

**Comment by taiki-e** [comment]
Filed #175. Could you confirm that it is the interface you were expecting?

**Comment by leighmcculloch** [comment]
Oh wow that was fast. Taking a look 👀.
