### ISSUE TITLE
Provide a way to run --each-feature without --no-default-features

### ISSUE THREAD

**Issue by jaskij** [taiki-e/cargo-hack#194]
I'm writing a multicall binary, where each sub-program is a separate feature. As such, building my program with no features just doesn't make sense.

I would like to run `cargo-hack` to check/build/test each feature, but exclude `--no-default-features`.

**Comment by taiki-e** [comment]
I think you can use --exclude-no-default-features.

```
        --exclude-no-default-features
            Exclude run of just --no-default-features flag.

            This flag can only be used together with either --each-feature flag or
            --feature-powerset flag.
```

**Comment by jaskij** [comment]
Ah, thank you, that works. I was looking at the docs over at crates.io rather then in `--help`.

**Comment by taiki-e** [comment]
> crates.io rather then in `--help`

FWIW, click on the "Click to show a complete list of options" in the ["Usage" section](https://github.com/taiki-e/cargo-hack#usage) of crates.io and readme to see the full `--help` output.

**Comment by jaskij** [comment]
Ah, thank you. I missed that, overlooked that.

Just my opinion, but I think at least the shorter `-h` (clap shows short output for `-h` and long for `--help`) output should be unspoilered, to have better discoverability via text search.
