### ISSUE TITLE
Flag to run cargo commands with the appropriate MSRV

### ISSUE THREAD

**Issue by epage** [taiki-e/cargo-hack#196]
I'm imagining a `--rust-version` flag that would add a `+<package.rust-version>` to each underlying cargo invocation.

**Comment by epage** [comment]
Sometimes there is a different MSRV for development and release.  I think a good next step past this is a flag to run `cargo package` on each workspace member, extract, patch, and then build those

Mentioning this now for the smaller issue in case it affects the CLI design for this one

**Comment by taiki-e** [comment]
Thanks for the suggestion! 

I think `--version-range .. --version-step <large number>` can do something similar, but it makes sense to have a dedicated flag.

https://github.com/taiki-e/cargo-hack#--version-range


> If the lower bound of the range is omitted, the value of the rust-version field in Cargo.toml is used as the lower bound.
> 
> You can specify the version interval by using --version-step.

**Comment by epage** [comment]
Oh, interesting.  I agree that a short-hand for this would also be useful.

I can go add this if you are ok (which it sounds like)

**Comment by taiki-e** [comment]
> I can go add this if you are ok (which it sounds like)

Thanks. I would be happy to accept a PR to add this.
