### ISSUE TITLE
Use rust syntax for version ranges

### ISSUE THREAD

**Issue by epage** [taiki-e/cargo-hack#197]
> Perform commands on a specified (inclusive) range of Rust versions.
> 
> ```console
> $ cargo hack check --version-range 1.46..1.47
> ```

Being used to rust, the use of an inclusive range for `..` seems odd rather than `..=`. 

Granted, this would be a breaking change.

**Comment by taiki-e** [comment]
Indeed.

> Granted, this would be a breaking change.

I have no plans to support (half) exclusive range, so I think we can simply deprecate the current one and warn on it.
