### ISSUE TITLE
A flag to only verify published packages

### ISSUE THREAD

**Issue by epage** [taiki-e/cargo-hack#204]
When testing against "everything" (packages, powerset of features, multiple rust versions), that is generally done because you want to ensure your code works for the consumers of your API.  The downside to this is it is expensive to hit every case.

Since the target is on the consumers, one way of speeding things up is to only verify the packages that will be consumed.  For example, we could add a `--published` flag that is like `--workspace` except packages with `package.publish = false` would automatically be excluded.

**Comment by taiki-e** [comment]
There are --ignore-private and --no-private.

https://github.com/taiki-e/cargo-hack#--ignore-private

> ### --ignore-private
> Skip to perform on publish = false crates.
> 
> ### --no-private
> Perform without publish = false crates. This is similar to --ignore-private, but is more powerful because this also prevents private crates from affecting lockfile and metadata.
> 
> Note: --no-private flag modifies Cargo.toml while cargo-hack is running and restores it when finished.

**Comment by epage** [comment]
Oh, missed that
