### ISSUE TITLE
Easier-to-browse logs in CI

### ISSUE THREAD

**Issue by epage** [taiki-e/cargo-hack#205]
Modern CIs group all of the output for a command, making it easy to see cause-and-affect but this breaks down when there are "do everything" commands.

Some CI systems support special output directives so commands can provide their own grouping, e.g. [github](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines).  I feel like detecting a CI system and emitting these directives would improve the experience of using cargo-hack.

Downsides
- Piecemeal support for different CI systems as they implement it and cargo-hack supports it
- Raw logs will have extra chatter

**Comment by taiki-e** [comment]
Thanks for the suggestion! I've experimented with this in #206, and it looks great.

<img width="778" alt="ss" src="https://github.com/taiki-e/cargo-hack/assets/43724913/f0fa7cb7-a966-4b10-8d6c-3d479e23cc48">
