### ISSUE TITLE
`cargo hack check` downloads unneeded target specific dependencies

### ISSUE THREAD

**Issue by rukai** [taiki-e/cargo-hack#223]
I was investigating ways to get our CI disk usage within github actions ~16GB limit and discovered that about 100MB of target specific dependencies was being downloaded by cargo hack.

Using parking_lot as an example since its a lot smaller than my own crate.
Run the following on linux:
```shell
rm -r ~/.cargo/registry
git clone https://github.com/Amanieu/parking_lot
cd parking_lot

cargo check
ls ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/
# observe the dependencies downloaded by cargo here.

cargo hack check
ls ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/
# Observe that dependencies for unused features are pulled in.
# This is fine by me as I only use cargo-hack for its `--feature-powerset` functionality anyway.
# But also observe that windows and redox specific dependencies are now downloaded.
# This is problematic because those dependencies will never be used on linux.
# Cargo does not download these dependencies on linux because of the lines like `[target.'cfg(windows)'.dependencies]` in the Cargo.toml
```

**Comment by taiki-e** [comment]
Perhaps it is due to the `cargo metadata` without --no-deps (called by `cargo hack`) or the v1 resolver. In the former case, `--filter-platform` may fix the problem.

**Comment by taiki-e** [comment]
Fixed in 0.6.9.

**Comment by rukai** [comment]
Thankyou!

I can confirm 0.6.9 fixed the issue.
Both unused feature dependencies and unused target based dependencies are no longer downloaded.

**Comment by taiki-e** [comment]
As a follow-up, since 0.6.11 just released, cargo-metadata called in cargo-hack no longer downloads dependencies except when using `--include-deps-features` (which is actually a mostly deprecated option). This means that only what is really needed is now downloaded at build time.
