### ISSUE TITLE
Exclude features using implicit features that are mutually exclusive

### ISSUE THREAD

**Issue by audunhalland** [taiki-e/cargo-hack#244]
```
[features]
a = []
b = ["a"]
c = []
```

`cargo hack --feature-powerset --mutually-exclusive-features a,c test`

Should this test `b` and `c` in combination? I'm not sure, but initial feeling is that it could be a bug, since `b` implies `a`. My `cargo hack` tests generates too many useless combinations because of this.

Also this example is probably over-simplified compared to my actual setup, but I wanted to get clarity on the intended behaviour first.

Feel free to close this if it's a feature rather than a bug.

**Comment by taiki-e** [comment]
Fixed in 0.6.25.

**Comment by audunhalland** [comment]
Amazingly quick fix :) Thank you. It seems to work very well. My configuration count went down from 68 to 18.
