### ISSUE TITLE
Start `--feature-powerset` with `--all-features`

### ISSUE THREAD

**Issue by newpavlov** [taiki-e/cargo-hack#246]
When used as part of CI it's beneficial for `cargo hack` to fail early. If crate has a failing feature, then tests are likely to fail on `cargo test --all-features`, so it arguably makes sense for `cargo hack` to start with it and only after it has succeeded to continue check other feature combinations. If `--exclude-features` is used, then we should start with the biggest number of allowed features.

Relevant issue: https://github.com/RustCrypto/actions/issues/40

**Comment by taiki-e** [comment]
Opened https://github.com/taiki-e/cargo-hack/pull/247 to implement this.

**Comment by taiki-e** [comment]
Implemented in 0.6.27 (#247).
