### ISSUE TITLE
[bug] v0.6.27 runs all-features before powerset but ignores mutually-exclusive-features

### ISSUE THREAD

**Issue by e1732a364fed** [taiki-e/cargo-hack#250]
Problem:
It seems that some new code in 0.6.27 runs all-features before powerset, but it ignores mutually-exclusive-features

Proof:

See the github action log in my project:

0.6.27: break
https://github.com/e1732a364fed/ruci/actions/runs/8679836216/job/23799420486

restrict cargo hack version to 0.6.26: test ok
https://github.com/e1732a364fed/ruci/actions/runs/8679872586/job/23799558747

In my project I used mlua, it provides both "luau" and "lua54" features, but only one can be enabled.

**Comment by e1732a364fed** [comment]
I think it's related to :
https://github.com/taiki-e/cargo-hack/pull/247

**Comment by taiki-e** [comment]
Thanks for the report. The relevant logic was always wrong since the implementation of mutually-exclusive-features, but before #247 it was not easy to trigger.

**Comment by taiki-e** [comment]
Fixed in 0.6.28.
