### ISSUE TITLE
request: Add enumeration diagnostics to output

### ISSUE THREAD

**Issue by kentfredric** [taiki-e/cargo-hack#27]
When using --each-feature or --feature-powerset, its not often clear where the progress is in the overall scheme of things.

It would be nice if these flags added diagnostic info showing something like:

```
info: `cargo hack --each-feature` target 4 of 10
```
```
info: `cargo hack --each-feature` target 4 of 300
```

**Comment by taiki-e** [comment]
Fixed in 0.3.4.
