### ISSUE TITLE
request: option to also enumerate second-order features

### ISSUE THREAD

**Issue by kentfredric** [taiki-e/cargo-hack#29]
A little known thing is you can do:

```
 cargo test --features "foo/bar"
```

Which activates the "bar" feature of the "foo" crate. ( it makes sense when you see how features are defined in Cargo.toml ).

Subsequently, this means there is a way to expand test coverage to test situations where somebody turns on that feature in a different crate, and you get it through cargo composition.

So it would be nice if there was a way to test these, understandably, the set size it may generate could be prohibitively large in some cases, so its not a sensible default.

**Comment by taiki-e** [comment]
Added in 0.4.0 (#70).
