### ISSUE TITLE
Should --each-feature and --feature-powerset run --all-features?

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-hack#42]
default/no-default features are already included, so all-features also need to be included?

**Comment by taiki-e** [comment]
It would make sense for `--feature-powerset` to include this, because `--all-features` is one of the combinations of features. (I'm not sure about `--each-feature` should do this or not.) 

Also, if `--skip` is passed, then `--all-features` should be skipped.

**Comment by taiki-e** [comment]
> Also, if `--skip` is passed, then `--all-features` should be skipped.

Nah, it's not clear how this should interact with #48.

**Comment by taiki-e** [comment]
I prefer to do this on both flags and to add `--skip-all-features` flag, as said in #48.

**Comment by jhpratt** [comment]
With regard to all-features, why does this need to be included, given that it's inherently already part of the powerset? Likewise for no-default-features. I found the previous behavior odd, and was surprised to learn that it was expanded.

**Comment by taiki-e** [comment]
@jhpratt I don't remember if it is exactly the same at this time, but all-features will behave differently than a normal combination of features, at least in the future (https://github.com/rust-lang/cargo/pull/8799).
For no-default-feature, should be fixed in #77 (previous behavior is wrong).

**Comment by jhpratt** [comment]
Neat. I didn't realize namespaced features were progressing. Thanks for the info.

**Comment by taiki-e** [comment]
That said, I think #61 implemented this in a somewhat wrong way.
Probably `--all-features` should not be included in the combination if some features have already excluded by `--exclude-features` (`--skip`).

**Comment by taiki-e** [comment]
I think #141 (published in 0.5.9) has fixed the rest of the problems here.
