### ISSUE TITLE
Ability to include crates as feature flags (for --feature-powerset)

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#50]
Would it be possible to have the ability to pretend a feature flag is defined in Cargo.toml for certain crates? I have serde & rand implementations behind a flag. As cargo will implicitly pass a flag with the crate's name, this is common practice.

Perhaps something along the line of `--feature-powerset-includes=serde,rand`? It's a bit verbose, but provides clarity on what exactly is occurring. Having the ability to ignore certain combinations in the powerset would also be nice, but I'm not sure what form that would take.

**Comment by jhpratt** [comment]
Disregard! I see the `--optional-deps` flag that can be provided. I should have looked at `cargo hack --help` and not just the documentation on crates.io before filing this.

**Comment by taiki-e** [comment]
follow-up: Added link to output of `cargo hack --help` to readme (https://github.com/taiki-e/cargo-hack/commit/854596fd8f65a3b7d1b22a0e2144c5e46dd9a28a). 
Here is actual help messages: [long(`--help`)](https://github.com/taiki-e/cargo-hack/blob/master/tests/long-help.txt),  [short(`-h`) ](https://github.com/taiki-e/cargo-hack/blob/master/tests/short-help.txt)
