### ISSUE TITLE
Idea: add flag to test all feature flag permutation w/ a max # of simultaneous feature flags

### ISSUE THREAD

**Issue by carllerche** [taiki-e/cargo-hack#58]
maybe `--feature-powerset --depth 2`.

Tokio has too many features to test the power set. However, **most** issues can be reproduced by testing at most 2 features simultaneously. It would be nice to have a feature that tested all permutations of **at most** N simultaneous feature flags. This would catch most problems.

**Comment by taiki-e** [comment]
Added in cargo-hack 0.3.14 (#59).
